stages:
  split:
    cmd: python src/data/split.py
    deps:
    - data/raw/raw.csv
    - src/data/split.py
    outs:
    - data/processed/X_test.csv
    - data/processed/X_train.csv
    - data/processed/y_test.csv
    - data/processed/y_train.csv
  scale:
    cmd: python src/data/scale.py
    deps:
    - data/processed/X_test.csv
    - data/processed/X_train.csv
    - src/data/scale.py
    outs:
    - data/processed/X_test_scaled.csv
    - data/processed/X_train_scaled.csv
    - models/scaler.pkl
  gridsearch:
    cmd: python src/models/gridsearch.py
    deps:
    - data/processed/X_train_scaled.csv
    - data/processed/y_train.csv
    - src/models/gridsearch.py
    outs:
    - models/best_params.pkl
  train:
    cmd: python src/models/train.py
    deps:
    - data/processed/X_train_scaled.csv
    - data/processed/y_train.csv
    - models/best_params.pkl
    - src/models/train.py
    outs:
    - models/model.pkl
  evaluate:
    cmd: python src/models/evaluate.py
    deps:
    - data/processed/X_test_scaled.csv
    - data/processed/y_test.csv
    - models/model.pkl
    - src/models/evaluate.py
    outs:
    - data/predictions.csv
    metrics:
    - metrics/scores.json:
        cache: false
